# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 5
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: NAUGHTY CHEN
description: "A jekyll website for Zhuohan Chen"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: https://paaandachen.github.io
# baseurl: ""

google_analytics: UA-72359418-1
repo: https://github.com/PaaandaChen/PaaandaChen.github.io
disqus_shortname: "Zhuohan Chen"
disqus_site_shortname: "naughtychen-cc"

# Author settings
author:
  name: Zhuohan Chen
  job: master student
  location: CMLab
  bio: "Interested in computer graphics, computer vision, VR/AR, light field, etc."
  thumb: /images/author_120x120.jpg
  email: pandachen0611@gmail.com
  url: https://paaandachen.github.io
  github: https://github.com/paaandachen
  facebook: https://www.facebook.com/chen.zhuohan
  instagram: https://www.instagram.com/thegreatgreatpanda/

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: icons
  #   title: Icons
  - slug: blog
    title: Projects

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
